[project]
name = "content-creator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.11.3",
    "mcp[cli]>=1.13.1",
    "openai>=1.101.0",
    "python-a2a>=0.5.9",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
]
